jwtpassword:
  source: ENC(foTHOXMs3+XPmFWjU982ZSZl/HmV971ViWri+mqf/+s/EQ8cCb/0uNoIMOnIv52H/BI8X4+EIQojuAeuXCXB/7gzCKMj8Z6dOpR9asKKEOY=)

jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}

oauth:
  kakao:
    client-id: ENC(dGY5idd3p5BT7SmM3jAzcOUtcHM6HNAEuE6unhGyusOBtwmbWGRD/j2GHjuNr+AK)
    secret: ENC(tkjxfDY5EHsJlm4hRHqoyCRpnAMsSfUzFgEkC55ssu6VsSrkZts94USxxeYFlnlI)
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
      redirect-uri: http://localhost:8080/api/auth/kakao

spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  jpa:
    open-in-view: false
    show-sql: true
  datasource:
    username: ENC(h2JOcqwlTgH7EViYp44e4g==)
    password: ENC(FZchWcTilrdnJpcRebDLtOL5eTdyhz1T)
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/RunningCrewDB
    server-url: ENC(iDTg6Fxw1LNDNw/voQuAhia2p7Xt0CLQZeYH2znQGFSx9qZqed4wJeaw2TjQ4lfauEVSXb5F36ZXoPjllIHkbw==)


  data:
    redis:
      host: localhost
      port: 6379


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /running-docs.html
  version: 1.0.0

