jwtpassword:
  source: ENC(foTHOXMs3+XPmFWjU982ZSZl/HmV971ViWri+mqf/+s/EQ8cCb/0uNoIMOnIv52H/BI8X4+EIQojuAeuXCXB/7gzCKMj8Z6dOpR9asKKEOY=)
logging:
  level:
    org:
      springframework:
        web:
          socket: DEBUG
        messaging: DEBUG
jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}

map:
  kakao:
    rest-api-key: ENC(cQN/WpKnYjJBWjBW04vysFl+5LLsk8eHoTBXKHjzqMB4ZldMG6rJ4PjAXm1QifW2)

oauth:
  kakao:
    client-id: ENC(dGY5idd3p5BT7SmM3jAzcOUtcHM6HNAEuE6unhGyusOBtwmbWGRD/j2GHjuNr+AK)
    secret: ENC(tkjxfDY5EHsJlm4hRHqoyCRpnAMsSfUzFgEkC55ssu6VsSrkZts94USxxeYFlnlI)
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
      redirect-uri: http://localhost:8080/api/auth/kakao
  naver:
    client-id: ENC(ViBdn4cYnxMFSXi0rSs7mnrQBwlfRHzxJnXVbTw7YSE=)
    secret: ENC(YEL+R3qWDgfscQvMgwa1yJN6x/NGOZeq)
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com

spring:
  profiles:
    include: aws
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  jpa:
    open-in-view: false
  datasource:
    username: ENC(h2JOcqwlTgH7EViYp44e4g==)
    password: ENC(FZchWcTilrdnJpcRebDLtOL5eTdyhz1T)
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-1.cto824g8iqv2.ap-northeast-2.rds.amazonaws.com:3306/RunningCrewDB
    server-url: ENC(FbdGmh5s9GqK90JAkn5qEDVac2WmEsOYGi9QRiDRC41RY7Ir2CkUiBMnQJz/vl7exzhR+8sLDwpHtxljpCHuyFFa9B6eMhtJ9IQ7dMcNT7g=)
    https-server-url: ENC(11eV7R5ZYYLEEcpgiu2GbmdWsvf+3N7MXzrcdn1dvn8=)
    hikari:
      max-lifetime: 30000
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: ENC(ZXsw7oaZXEdF+xz0JNOb1KW8DrKs5DOJlAQpOI/DCBvWUyJYl8FbhN5BWeVxsK2eXoD1TeEaqxseSqNoLZB818YvxmRDaR+W4ktr5VpEx7UjiNIcwifbLVlURfS8KlOEt8UE+sbuJNgAFdws+HbxgnhnxGvEJ+MK)
      database: RunningCrewChat

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: alarm-group # 컨슈머 그룹 ID
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
      acks: all
      batch-size: 16384
      linger-ms: 1
      buffer-memory: 33554432
    admin:

      properties:
        retry.backoff.ms: 5000   # 재시도 대기 시간
        request.timeout.ms: 30000  # 요청 타임아웃 시간 (30초)
        timeout: 60s # 전체 타임아웃 시간 설정
    topic:
      new-entity-topic: alarm-topic # 실제 토픽 이름 설정

  mail:  #메일설정
    host: smtp.gmail.com
    port: 587
    username: ENC(tZCNtUD39C1X4xxr3+oP0HZ0q95nukRsjUP0oqK3jOw=)
    password: ENC(yymAj4wB0P5Hy3w4p5kBeV7dImkHJWaYqBtHPX2C3EI=)
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  #              Identity Manager 서버가 SSL을 사용하여 SMTP와 통신하도록 지시합니다.
  jackson:
    time-zone: Asia/Seoul #time-zone 한국으로 설정


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /running-docs.html
  version: 1.0.0

