jwtpassword:
  source: ENC(foTHOXMs3+XPmFWjU982ZSZl/HmV971ViWri+mqf/+s/EQ8cCb/0uNoIMOnIv52H/BI8X4+EIQojuAeuXCXB/7gzCKMj8Z6dOpR9asKKEOY=)

jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}

oauth:
  kakao:
    client-id: ENC(dGY5idd3p5BT7SmM3jAzcOUtcHM6HNAEuE6unhGyusOBtwmbWGRD/j2GHjuNr+AK)
    secret: ENC(tkjxfDY5EHsJlm4hRHqoyCRpnAMsSfUzFgEkC55ssu6VsSrkZts94USxxeYFlnlI)
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
      redirect-uri: http://localhost:8080/api/auth/kakao

spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  datasource:
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-1.cto824g8iqv2.ap-northeast-2.rds.amazonaws.com:3306/RunningCrewDB

  data:
    redis:
      host: localhost
      port: 6379


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /amp-docs.html
  version: 1.0.0

